### ISSUE TITLE
A quick question: can you reverse this process, letting face control the joystick 

### ISSUE THREAD

**Issue by michael7908** [maHidaka/ros_face#12]
maHidaka san, your masterpiece is impressive.

While I am thinking about is that  if you may control your console or joystick with your facial expression? 

So some paralyzed patient may enjoy game too...

Just my thought and thank you again.

**Comment by maHidaka** [comment]
Hello, Michael7908-san,

Thank you for your feedback. The technology of reading muscle movements with a computer and using it for game control is more common than this project, and it has been widely adopted in recent years. Electromyography (EMG) sensing technology has significantly advanced in the past few years, and it seems that it can even read brainwaves.

**Comment by michael7908** [comment]
Hi  MaHidaka-San,

Thank you for your detailed and informative response.

I wish you a Merry Christmas and a Happy New Year!

Michael
