### ISSUE TITLE
whats the voltage of vcc

### ISSUE THREAD

**Issue by hlcm0** [maHidaka/ros_face#8]
could you tell me the voltage of vcc？

**Comment by maHidaka** [comment]
It is approximately 9~15VDC.
The voltage required varies a bit depending on the body part.
For hands and feet, about twice as much voltage is required.
Electrodes are easy to use with salt water.

**Comment by hlcm0** [comment]
thankyou

**Comment by tong-ge** [comment]
Only 15V?!!!How can these harmless voltages affect human bodies?
