### ISSUE TITLE
一眼假

### ISSUE THREAD

**Issue by XRFXRF** [maHidaka/ros_face#9]
这个项目唯一的难点在于外部电刺激能否如此精准地控制面部肌肉，在我看来，你只能接收人产生的电信号，而不可能如此精准地通过电刺激来控制肌肉收缩。

**Comment by maHidaka** [comment]
I do not understand Chinese, so I cannot read your claim accurately.

The project is to apply the control technology used in robotics to human control and release it as open source.
And as an example of the results of this project, I have released a promotional video.

Hardware and software configurations are available to the public, which will help you to reproduce the experiment.
I will continue to provide you with the information you need to use this project.

If you have any problems or questions, feel free to ask the issue.

**Comment by ImKK666** [comment]
> 这个项目唯一的难点在于外部电刺激能否如此精准地控制面部肌肉，在我看来，你只能接收人产生的电信号，而不可能如此精准地通过电刺激来控制肌肉收缩。

测试过吗?

**Comment by ITACMI** [comment]
测试过再说话
Talk after the test

**Comment by awgf1234556** [comment]
Can you publish the pbc file, here is only the principle image
能公布一下pbc文件吗？

**Comment by maHidaka** [comment]
@awgf1234556  Your question is different from this already closed issue, so you should make a new issue.

**Comment by awgf1234556** [comment]
> @awgf1234556 Your question is different from this already closed issue, so you should make a new issue.

right
